# Generated by Django 6.0.6 on 2026-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
    ]
