# Generated by Django 6.0.6 on 2026-07-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('ram', 'RAM'), ('motherboard', 'Motherboard'), ('storage', 'Storage'), ('power_supply', 'Power Supply'), ('case', 'Case'), ('cooling', 'Cooling'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
